### ISSUE TITLE
reconciler-runtime with kcp's controller-runtime?

### ISSUE THREAD

**Issue by KauzClay** [reconcilerio/runtime#557]
This is more of a question than an issue, but:

 Would you expect reconciler-runtime to just "plug in" in the context of kcp?

I learned recently that kcp has a forked version of controller-runtime: https://github.com/kcp-dev/controller-runtime

I tried writing a basic controller-runtime style reconciler with the kcp controller-runtime, and that seemed to run. But when I tried to swap that out for a reconciler-runtime style one (just dropped it in with SetupWithManager), it didn't seem to get called when I created the resource it was supposed to reconcile.

I still don't really understand how controller-runtime was changed for kcp, so I don't have a more detailed question at the moment.

But, I was just curious if anyone here has thought about this. Thanks!

**Comment by nebhale** [comment]
Hey there!  I've done some experimentation with this and while I don't have a perfect map for you, I will tell you that it's a lot easier than I thought it was going to be.  My recollection is that there are three big components that are important for you to take into account:

# 1. Replace controller runtime
My (very dated) `go.mod` included the following stanzas.  The important bits were the first two lines (getting the kcp types available to you) and the final line where you replace the standard controller-runtime with kcp's controller-runtime fork.

```
require (
    github.com/kcp-dev/kcp/sdk v0.24.0
    github.com/kcp-dev/logicalcluster/v3 v3.0.5
    k8s.io/api v0.30.1
    k8s.io/apiextensions-apiserver v0.30.1
    k8s.io/apimachinery v0.30.1
    k8s.io/client-go v0.30.1
    reconciler.io/dies v0.12.0
    reconciler.io/runtime v0.20.1-0.20240528125453-597a9ed508c3
    sigs.k8s.io/controller-runtime v0.18.3
    sigs.k8s.io/yaml v1.4.0
)

replace (
    k8s.io/api => k8s.io/api v0.29.0
    k8s.io/apimachinery => k8s.io/apimachinery v0.29.0
    k8s.io/apiserver => k8s.io/apiserver v0.29.0
    k8s.io/client-go => k8s.io/client-go v0.29.0
    sigs.k8s.io/controller-runtime => github.com/kcp-dev/controller-runtime v0.17.2-kcp.2
)
```

# 2. Make sure you use a `ClusterAwareManager`
A lot of the magic of virtual clusters is [papered over with a simple round-tripper](https://github.com/kcp-dev/controller-runtime/blob/fd7cd5b37379dc5feadbbd5385572e2a4cb63832/pkg/kcp/wrappers.go#L214-L220) in kcp's `ClusterAwareManager`.

```go
mgr, err := kcp.NewClusterAwareManager(...)
```

# 3.  Populate the context with logical cluster name
For the life of me I can't remember why this is so critical to do, but there's an entire [wrapper function for "conventional" reconcilers](https://github.com/kcp-dev/controller-runtime/blob/fd7cd5b37379dc5feadbbd5385572e2a4cb63832/pkg/kcp/helper.go#L29).  My way out of this was to add it as a `BeforeReconcile()` function in my `ResourceReconciler`:

```go
BeforeReconcile: func(ctx context.Context, req reconcilers.Request) (context.Context, reconcilers.Result, error) {
    return kontext.WithCluster(ctx, logicalcluster.Name(req.ClusterName)), reconcilers.Result{}, nil
},
```

And that's it (as I remember).  I believe I was able to otherwise use a standard `ResourceReconciler` at this point.

**Comment by KauzClay** [comment]
so, I followed @nebhale  steps above, and things worked!

Steps 2 and 3 are definitely what you need. For step 1, I think that may vary depending on where you're inserting this.

In my case, the repo I'm working in was using `github.com/kcp-dev/controller-runtime v0.16.3`. I was able to get away with `reconciler.io/runtime v0.22.0` at first. I could compile and run and see my reconciler get triggered when I created a resource.

However, when I wanted to use dies for testing, things got a little messy. I think the k8s version assumed in kcp's controller-runtime at v0.16.3 is too old for the newest reconciler runtime. Still trying to figure out the compatible versions I need to get that to work. 

I think its more of a problem to my environment than this broader issue, but I'll still follow up here if I sort it out.

**Comment by scothis** [comment]
> However, when I wanted to use dies for testing, things got a little messy. I think the k8s version assumed in kcp's controller-runtime at v0.16.3 is too old for many of the recent versions of reconciler runtime/dies. Still trying to figure out the compatible versions I need to get that to work.

`dies.dev` the precursor to `reconciler.io/dies` has support back to Kubernetes 1.22 types. The latest version of the kcp controller-runtime is compatible with the latest `reconciler.io/dies` and k8s 1.31 types

**Comment by scothis** [comment]
Closing as there doesn't appear to be any direct action needed. Feel free to continue the conversation.
